name: CD Pipeline

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull $DOCKER_USER/titanic-fastapi:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f titanic-fastapi-container || true
    
      - name: Run Docker Container
        run: sudo docker run -it -d -p 8080:8080 --name titanic-fastapi-container $DOCKER_USER/titanic-fastapi:latest
